mod_id=dthexerei
mod_name=DynamicTreesHexerei
mod_license=MIT
mod_version=1.3.0
mod_group_id=com.maxhyper.dthexerei
mod_authors=Max Hyper
mod_description=Dynamic Trees compatibility for Hexerei

minecraft_version=1.21.1
neoforge_version=21.1.248
neoforge_loader_version_range=[4,)
minecraft_version_range=[1.21.1]

dynamictrees_version=1.7.2
hexerei_version=0.5.0.3

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
